version: '2'
services:
  postgreshost:
    image: postgres:9.4.1
    ports:
      - "5432:5432"

  box:
    image: busybox
    volumes:
      - /box

  puma_web:
    build: .
    command: sh -c "bundle install && bundle exec puma -C config/puma.rb"
    ports:
      - "3000:3000"
    links:
      - postgreshost
    volumes:
      - .:/app
    volumes_from:
      - box

  unicorn_web:
    build: .
    command: sh -c "bundle install && bundle exec unicorn -c config/unicorn.rb"
    ports:
      - "3000:3000"
    links:
      - postgreshost
    volumes:
      - .:/app
    volumes_from:
      - box

  tcell_puma_web:
    build: .
    command: sh -c "bundle install && bundle exec puma -C config/puma.rb"
    ports:
      - "3000:3000"
    links:
      - postgreshost
    volumes:
      - .:/app
      - ./docker/Gemfile.released:/app/Gemfile
    volumes_from:
      - box

  tcell_unicorn_web:
    build: .
    command: sh -c "bundle install && bundle exec unicorn -c config/unicorn.rb"
    ports:
      - "3000:3000"
    links:
      - postgreshost
    volumes:
      - .:/app
      - ./docker/Gemfile.released:/app/Gemfile
    volumes_from:
      - box

  tcell_puma_local_web:
    build: .
    command: sh -c "bundle install && bundle exec puma -C config/puma.rb"
    ports:
      - "3000:3000"
    links:
      - postgreshost
    volumes:
      - ../rubyagent-tcell/ext:/tcellagent_src/ext
      - ../rubyagent-tcell/lib:/tcellagent_src/lib
      - ../rubyagent-tcell/bin:/tcellagent_src/bin
      - ../rubyagent-tcell/Gemfile:/tcellagent_src/Gemfile
      - ../rubyagent-tcell/Gemfile.lock:/tcellagent_src/Gemfile.lock
      - ../rubyagent-tcell/tcell_agent.gemspec:/tcellagent_src/tcell_agent.gemspec
      - ../rubyagent-tcell/LICENSE:/tcellagent_src/LICENSE
      - ../rubyagent-tcell/Rakefile:/tcellagent_src/Rakefile
      - .:/app
      - ./docker/Gemfile.dev:/app/Gemfile
    volumes_from:
      - box

  tcell_unicorn_local_web:
    build: .
    command: sh -c "bundle install && bundle exec unicorn -c config/unicorn.rb"
    ports:
      - "3000:3000"
    links:
      - postgreshost
    volumes:
      - ../rubyagent-tcell/ext:/tcellagent_src/ext
      - ../rubyagent-tcell/lib:/tcellagent_src/lib
      - ../rubyagent-tcell/bin:/tcellagent_src/bin
      - ../rubyagent-tcell/Gemfile:/tcellagent_src/Gemfile
      - ../rubyagent-tcell/Gemfile.lock:/tcellagent_src/Gemfile.lock
      - ../rubyagent-tcell/tcell_agent.gemspec:/tcellagent_src/tcell_agent.gemspec
      - ../rubyagent-tcell/LICENSE:/tcellagent_src/LICENSE
      - ../rubyagent-tcell/Rakefile:/tcellagent_src/Rakefile
      - .:/app
      - ./docker/Gemfile.dev:/app/Gemfile
    volumes_from:
      - box
